-- CreateTable
CREATE TABLE `vendors` (
    `id` VARCHAR(191) NOT NULL,
    `vendorId` VARCHAR(255) NOT NULL,
    `userId` VARCHAR(255) NOT NULL,
    `storeName` VARCHAR(255) NOT NULL,
    `phone` VARCHAR(50) NULL,
    `email` VARCHAR(255) NULL,
    `address` TEXT NULL,
    `vendorProfileImage` VARCHAR(500) NULL,
    `vendorBannerImage` VARCHAR(500) NULL,
    `inventoryCount` INTEGER NOT NULL DEFAULT 0,
    `categories` JSON NOT NULL,
    `description` TEXT NULL,
    `status` VARCHAR(50) NOT NULL DEFAULT 'pending',
    `storeEnabled` BOOLEAN NOT NULL DEFAULT true,
    `coupons` JSON NOT NULL,
    `storeCurrency` VARCHAR(10) NULL,
    `timezone` VARCHAR(100) NULL,
    `workHours` VARCHAR(255) NULL,
    `state` VARCHAR(255) NULL,
    `city` VARCHAR(255) NULL,
    `localGovernment` VARCHAR(255) NULL,
    `country` VARCHAR(255) NULL,
    `storeIndustries` JSON NOT NULL,
    `storeAddress` TEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `vendors_vendorId_key`(`vendorId`),
    INDEX `vendors_vendorId_idx`(`vendorId`),
    INDEX `vendors_userId_idx`(`userId`),
    INDEX `vendors_status_idx`(`status`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
